name: Calculate file hash1
'on':
  push:
    branches:
      - master
    paths-ignore:
      - '**/file_hash.txt'
jobs:
  file_hash:
    runs-on: self-hosted
    steps:
      - name: Run your workflow steps
        uses: actions/checkout@v4
        with:
          repository: Encryption-Consulting-LLC/Build-Verification
          path: ''
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: main
        
      - name: Forming the command to execute
        id: cal_hash
        run: echo "::set-output name=hash_cmd::$GITHUB_WORKSPACE/build-verifier-on-checkin.py $GITHUB_WORKSPACE"
        
      - name: Calculate the hash of all the files
        id: run_script
        run: ${{steps.cal_hash.outputs.hash_cmd}}

      - name: Check for errors
        run: |
          if [[ "${{ steps.run_script.outputs.stdout }}" == *"##[error]"* ]]; then
            echo "An error occurred: ${{ steps.run_script.outputs.stdout }}"
            exit 1  # Fail the workflow
          fi
