name: Calculate file hash3
'on':
  push:
    branches:
      - master
    paths-ignore:
      - '**/file_hash.txt'
jobs:
  file_hash:
    runs-on: self-hosted
    env:
      LOCAL_PATH: checkout
    steps:
      - name: Checkout the infrastructure code
        uses: actions/checkout@v4
        with:
          repository: Encryption-Consulting-LLC/Build-Verification
          path: ''
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: main
       
      - name: Checkout the code for which file hash needs to be calculated
        uses: actions/checkout@v4
        with:
          repository: ''
          path: ${{env.LOCAL_PATH}}
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: master
          
      - name: Forming the command to execute
        id: cal_hash
        run: |
          echo "::set-output name=hash_cmd::$GITHUB_WORKSPACE/build-verifier-on-checkin.py $GITHUB_WORKSPACE/${{env.LOCAL_PATH}} $GITHUB_REPOSITORY $GITHUB_REF_NAME"
          mkdir -p /tmp/build-verification/
        
      - name: Calculate the hash of all the files
        id: run_script
        run: ${{steps.cal_hash.outputs.hash_cmd}}

      - name: Check for errors
        run: |
          if [[ "${{ steps.run_script.outputs.stdout }}" == *"##[error]"* ]]; then
            echo "An error occurred: ${{ steps.run_script.outputs.stdout }}"
            exit 1  # Fail the workflow
          fi
