name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Optional description'
        required: false

jobs:
  file_hash:
    runs-on: self-hosted
    env:
      LOCAL_PATH: checkout
    steps:
      - name: Build the code
        uses: actions/checkout@v4
        with:
          repository: ''
          path: ${{env.LOCAL_PATH}}
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: master
      - name: Post build calculate hash of all the files
        uses: actions/checkout@v4
        with:
          repository: Encryption-Consulting-LLC/Build-Verification
          path: ''
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: main
          clean: false
      - name: Calculate the hash of all the files
        run: "${{env.GITHUB_WORKSPACE}}/build_verifier_on_build_trigger.py ${{env.GITHUB_WORKSPACE}}/${{env.LOCAL_PATH}} ${{env.GITHUB_REPOSITORY}} $GITHUB_REF_NAME"
      
