name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Optional description'
        required: false

jobs:
  file_hash:
    runs-on: self-hosted
    env:
      LOCAL_PATH: checkout
    steps:
      - name: Build the code
        uses: actions/checkout@v4
        with:
          repository: ''
          path: ${{env.LOCAL_PATH}}
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: master
          
      - name: Post build calculate hash of all the files
        uses: actions/checkout@v4
        with:
          repository: Encryption-Consulting-LLC/Build-Verification
          path: ''
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: main
          clean: false
          
      - name: Forming the command to execute
        id: verify_hash
        run: echo "::set-output name=hash_cmd::$GITHUB_WORKSPACE/build_verifier_on_build_trigger.py $GITHUB_WORKSPACE/${{env.LOCAL_PATH}} $GITHUB_REPOSITORY $GITHUB_REF_NAME"
        
      - name: Calculate the hash of all the files
        id: run_script
        run: ${{steps.check_push1.outputs.hash_cmd}}
        
      - name: Check for errors
        run: |
          if [[ "${{ steps.run_script.outputs.stdout }}" == *"##[error]"* ]]; then
            echo "An error occurred: ${{ steps.run_script.outputs.stdout }}"
            exit 1  # Fail the workflow
          fi
              
