name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Optional description'
        required: false

jobs:
  file_hash:
    runs-on: self-hosted
    env:
      LOCAL_PATH: checkout
    steps:
      - name: Build the code
        uses: actions/checkout@v4
        with:
          repository: ''
          path: ${{env.LOCAL_PATH}}
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: master
      - name: Post build calculate hash of all the files
        uses: actions/checkout@v4
        with:
          repository: Encryption-Consulting-LLC/Build-Verification
          path: ''
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: main
          clean: false
      - name: Calculate the hash of all the files
        id: run_command
        run: "$GITHUB_WORKSPACE/build_verifier_on_build_trigger.py $GITHUB_WORKSPACE/$LOCAL_PATH"
      - name: printing values
        run: |
          echo "dsdsdsd ---${{ steps.run_command.outputs.stdout }}"
      - name: Verify the hashes
        # Usage: verify.py repo_name branch_name file_hash_input
        run: echo "$GITHUB_WORKSPACE/verify_hash.py $GITHUB_REPOSITORY $GITHUB_REF_NAME  ${{ steps.get-hash.outputs.FILE_HASHES }}"
