name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Optional description'
        required: false

jobs:
  file_hash:
    runs-on: self-hosted
    env:
      LOCAL_PATH: hello
    steps:
      - name: Build the code
        uses: actions/checkout@v4
        with:
          repository: ''
          path: fdfd
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: master
          run: echo "$GITHUB_WORKSPACE"
      - name: Post build calculate hash of all the files
        uses: actions/checkout@v4
        with:
          repository: Encryption-Consulting-LLC/Build-Verification
          path: 
          token: ${{ secrets.BUILD_VERIFIER }}
          ref: main
      - name: Calculate the hash of all the files
        if: steps.check_push.outputs.push_by_specific_user == 'false'
        run: /tmp/runner/kubernetes-validating-webhook/kubernetes-validating-webhook/build-verifier-on-checkin.py
